export const ARGS_VALIDATION_ERROR = Symbol('ARGS_VALIDATION_ERROR')
export const UNAUTHORIZED = Symbol('UNAUTHORIZED')
export const MIDDLEWARE_AUTH_ERROR = Symbol('MIDDLEWARE_AUTH_ERROR')
export const MUST_BE_ANONYMOUS = Symbol('MUST_BE_ANONYMOUS')
