export const USER_REGISTERED = Symbol('USER_REGISTERED')
export const USER_LOGGED_IN = Symbol('USER_LOGGED_IN')
export const OWN_USER_FETCHED = Symbol('OWN_USER_FETCHED')
export const USER_LOGGED_OUT = Symbol('USER_LOGGED_OUT')

export const MUTATION_REGISTER_ERROR = Symbol('MUTATION_REGISTER_ERROR')
export const MUTATION_LOGIN_ERROR = Symbol('MUTATION_LOGIN_ERROR')
export const MUTATION_ME_ERROR = Symbol('MUTATION_ME_ERROR')
export const MUTATION_LOGOUT_ERROR = Symbol('MUTATION_LOGOUT_ERROR')

export const USERNAME_ALREADY_EXISTS = Symbol('USERNAME_ALREADY_EXISTS')
export const USER_NOT_FOUND = Symbol('USER_NOT_FOUND')
export const INCORRECT_PASSWORD = Symbol('INCORRECT_PASSWORD')
